import "../styles/globals.css";
import "../styles/BookingForm.scss";
import "../styles/Navbar.scss";
import "../styles/App.scss";
import "../styles/checkout.scss";
import "../styles/Footer.scss";
import Head from "next/head";
import Layout from "../components/Layout/Layout";
import { BookingContextProvider } from "./api/store";
import NextNProgress from "nextjs-progressbar";
export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Xecongnghe Booking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="keywords"
          content="taxi đường dài, taxi di tinh, taxi chieu ve, taxi đường dài giá rẻ, taxi sân bay, taxi san bay, taxi sân bay giá rẻ, taxi nội bài, Taxi Ha Noi Ninh Binh"
        />
        <link rel="icon" href="/images/logo-icon.png" />
      </Head>
      <BookingContextProvider>
        <Layout>
          <NextNProgress />
          <Component {...pageProps} />
        </Layout>
      </BookingContextProvider>
    </>
  );
}
